# Generated by Django 5.2.7 on 2025-10-21 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employees',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.TextField()),
                ('last_name', models.TextField(blank=True, null=True)),
                ('user_name', models.TextField(blank=True, null=True)),
                ('email', models.CharField(max_length=255)),
                ('password', models.TextField()),
                ('phone_number', models.TextField()),
                ('address', models.TextField()),
                ('profile_image_url', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.CharField(choices=[('0', 'inactive'), ('1', 'active'), ('5', 'deleted')], default='1', max_length=1)),
            ],
            options={
                'db_table': 'employees',
            },
        ),
        migrations.CreateModel(
            name='project_memberships',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.CharField(choices=[('0', 'inactive'), ('1', 'active'), ('5', 'deleted')], default='1', max_length=1)),
                ('member_id', models.ForeignKey(db_column='member_id', on_delete=django.db.models.deletion.CASCADE, to='my_app.employees')),
            ],
            options={
                'db_table': 'project_memberships',
            },
        ),
        migrations.CreateModel(
            name='projects',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('banner_image_url', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.CharField(choices=[('0', 'inactive'), ('1', 'active'), ('5', 'deleted')], default='1', max_length=1)),
                ('members', models.ManyToManyField(through='my_app.project_memberships', through_fields=('project_id', 'member_id'), to='my_app.employees')),
            ],
            options={
                'db_table': 'projects',
            },
        ),
        migrations.AddField(
            model_name='project_memberships',
            name='project_id',
            field=models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, to='my_app.projects'),
        ),
        migrations.AlterUniqueTogether(
            name='project_memberships',
            unique_together={('project_id', 'member_id')},
        ),
    ]
