# Generated by Django 5.2.7 on 2025-10-22 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
