# Generated by Django 5.2.7 on 2025-10-23 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_alter_employees_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_memberships',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
