# Generated by Django 5.2.7 on 2025-10-24 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_alter_project_memberships_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='phone_number',
            field=models.TextField(max_length=20),
        ),
    ]
