# Generated by Django 5.2.7 on 2025-10-24 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_alter_employees_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='title',
            field=models.TextField(unique=True),
        ),
    ]
