# Generated by Django 5.2.7 on 2025-10-24 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_alter_projects_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='title',
            field=models.TextField(),
        ),
    ]
