# Generated by Django 5.2.7 on 2025-10-27 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_alter_projects_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='messages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text_body', models.TextField(blank=True, null=True)),
                ('has_media', models.BooleanField(default=False)),
                ('media_url', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.CharField(choices=[('0', 'inactive'), ('1', 'active'), ('5', 'deleted')], default='1', max_length=1)),
                ('project_id', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.DO_NOTHING, to='my_app.projects')),
                ('sender_id', models.ForeignKey(db_column='sender_id', on_delete=django.db.models.deletion.DO_NOTHING, to='my_app.employees')),
            ],
            options={
                'db_table': 'messages',
            },
        ),
    ]
