# Generated by Django 5.2.7 on 2025-10-29 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
